name: Build and Deploy

on:
  push:
    branches:
      - dev
  
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    - name: Download artifact
      uses: actions/download-artifact@master
      with:
        name: app
    
    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          mkdir -p /home/ubuntu/myapp
          rm -rf /home/ubuntu/myapp/*
          cp app /home/ubuntu/myapp
          
