name: Build and deploy JAR app to Ubuntu Server

on:
  push:
    branches:
      - origin-master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    - name: Download artifact
      uses: actions/download-artifact@main
      with:
        name: app
        path: target
    
        
    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          mkdir -p /var/www/myapp
          rm -rf /var/www/myapp/*
          cp -r target/*.jar /var/www/myapp
