name: Build and Deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: self_hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Upload artifact  
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: target/*.jar

  deploy:
    needs: build
    runs-on: self_hosted
    steps:
    
    - name: Download artifact
      uses: actions/download-artifact@main
      with:
        name: java-app
        path: target
        
    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@dev
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          mkdir -p /tmp/app
          rm -rf /tmp/app*
          cp -r target/*.jar /tmp/app
